const fs = require('fs');
const path = require('path');
const vm = require('vm');
const root = path.resolve(__dirname, '..');
const context = {window:{}};
vm.runInNewContext(fs.readFileSync(path.join(root,'content.js'),'utf8'),context);
vm.runInNewContext(fs.readFileSync(path.join(root,'config.js'),'utf8'),context);
const configuredUrl=context.window.VORTEX_CONFIG?.siteUrl || '';
const baseUrl=configuredUrl && /^https?:\/\//.test(configuredUrl) ? configuredUrl.replace(/\/$/,'')+'/' : '';
const data = context.window.VORTEX_CONTENT;
const sectors = Object.entries(data.sectors);
const processes = Object.entries(data.processes);
const articles = data.articles;
const esc = value => String(value ?? '').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
const icon = (name, cls='') => '<i data-lucide="'+name+'" class="'+cls+'" aria-hidden="true"></i>';
const arrow = icon('arrow-right');
const link = (url,label,cls='line-link') => '<a class="'+cls+'" href="'+url+'">'+label+arrow+'</a>';
const label = (text) => '<p class="eyebrow">'+text+'</p>';
const routes = [
 ['home','index.html','首页'],['technology','technology.html','技术与产品'],
 ['sectors','sectors.html','应用领域'],['about','about.html','关于我们'],['research','research.html','研究动态']
];
const search = [];
const {videoCard,videoGallery,homeTechnology}=require("./video-sections.cjs");
function header(active) {
 return '<a class="skip" href="#main">跳至正文</a><header class="header"><a class="logo" href="index.html" aria-label="旋风流体首页"><img src="assets/vortex-symbol.svg" alt=""><span><strong>Tornado Fluid</strong><small>旋 风 流 体 科 技</small></span></a><nav class="nav" id="primary-nav" aria-label="主导航">'+routes.map(([id,url,title])=>'<a href="'+url+'" '+(active===id?'aria-current="page"':'')+'>'+title+'</a>').join('')+'</nav><div class="nav-actions"><button class="icon-button" id="search-open" type="button" aria-label="搜索网站" title="搜索网站">'+icon('search')+'</button><a class="language active" href="index.html" lang="zh-CN">中</a><a class="language" href="international.html" lang="en">EN</a>'+link('contact.html','联系我们','pill nav-contact')+'<button class="icon-button menu-toggle" aria-label="打开菜单" aria-expanded="false" aria-controls="primary-nav">'+icon('menu')+'</button></div></header>';
}
function footer(){
 return '<footer class="footer"><div class="container footer-top"><div>'+label('REAL FLUIDS. REAL IMPACT.')+'<h2>让流动创造<br>更多可能</h2><p>Tornado Fluid Technologies<br>旋风流体 · 悬浮空化技术</p></div><div class="footer-links"><div><h3>技术探索</h3><a href="technology.html">悬浮空化技术</a><a href="applications.html">工艺能力</a><a href="resources.html">资料中心</a></div><div><h3>应用领域</h3><a href="sector-food.html">食品与饮料</a><a href="sector-chemical.html">化工</a><a href="sector-environment.html">环境</a><a href="sectors.html">全部领域</a></div><div><h3>走近我们</h3><a href="about.html">关于旋风流体</a><a href="research.html">研究与动态</a><a href="contact.html">联系与咨询</a><a href="international.html">English overview</a></div></div></div><div class="container footer-bottom"><span>© 2026 Tornado Fluid Technologies</span><span><a href="privacy.html">隐私说明</a> / <a href="terms.html">使用条款</a></span><a class="top-link" href="#top">返回顶部 '+icon('arrow-up')+'</a></div></footer>';
}
function dialogs() {
 return '<dialog class="search-dialog" id="search-dialog" aria-labelledby="search-title"><div class="dialog-top"><h2 id="search-title">探索技术与应用</h2><button class="icon-button" data-close aria-label="关闭搜索">'+icon('x')+'</button></div><label class="search-input">'+icon('search')+'<input id="search-input" type="search" placeholder="搜索酒类、切削液、萃取…" autocomplete="off" aria-label="搜索关键词"></label><p class="search-hint" id="search-count" aria-live="polite">按技术、行业或工艺查找</p><div id="search-results"></div></dialog>';
}
function page(file,title,active,body,desc='旋风流体围绕悬浮空化技术，探索多行业工艺应用。',extra=''){
 const document='<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+esc(title)+' | 旋风流体 Tornado Fluid Technologies</title><meta name="description" content="'+esc(desc)+'"><meta name="theme-color" content="#edf2f4"><meta property="og:title" content="'+esc(title)+' · 旋风流体"><meta property="og:description" content="'+esc(desc)+'"><link rel="icon" href="assets/vortex-symbol.svg" type="image/svg+xml"><link rel="stylesheet" href="site.css?v=20260917-water1"></head><body id="top" class="'+(active==='home'?'home-page':'inner-page')+'"><div class="site-ambient water-background" aria-hidden="true"><div class="water-poster"></div></div>'+header(active)+'<main id="main">'+body+'</main>'+footer()+dialogs()+'<script src="assets/lucide.min.js"></script><script src="search-index.js"></script><script src="config.js"></script><script src="site.js"></script><script src="media-player.js"></script><script src="page-background.js?v=20260917-water1"></script>'+extra+'</body></html>';
 const canonical=baseUrl?'<link rel="canonical" href="'+esc(new URL(file,baseUrl).href)+'"><meta property="og:url" content="'+esc(new URL(file,baseUrl).href)+'">':'';
 fs.writeFileSync(path.join(root,file),document.replace('</head>',canonical+'</head>'));
 search.push({title,url:file,type:active,description:desc});
}
function crumbs(items){return '<nav class="breadcrumb" aria-label="当前位置"><a href="index.html">首页</a>'+items.map(([text,url])=>'<span>/</span>'+(url?'<a href="'+url+'">'+text+'</a>':'<span aria-current="page">'+text+'</span>')).join('')+'</nav>';}
function intro(kicker,title,text){return '<div class="section-intro"><div>'+label(kicker)+'<h2>'+title+'</h2></div><p>'+text+'</p></div>';}
function innerHero(kicker,title,text,image='assets/flow-hero.webp') {
 return '<section class="inner-hero"><img src="'+image+'" alt="" class="inner-back"><div class="container">'+label(kicker)+'<h1>'+title+'</h1><p>'+text+'</p></div></section>';
}
function metrics(labels){return '<div class="criteria">'+labels.map((x,i)=>'<div><small>0'+(i+1)+'</small><h3>'+esc(x)+'</h3></div>').join('')+'</div>';}
function sectorCards(){
 return '<div class="sector-grid">'+sectors.map(([key,s],i)=>'<a class="sector-card" href="sector-'+key+'.html"><div class="sector-image"><img loading="lazy" src="'+s.image+'" alt="'+esc(s.name)+'行业参考影像"><span>0'+(i+1)+' / '+esc(s.english)+'</span></div><div class="sector-copy"><h3>'+esc(s.name)+'</h3>'+arrow+'<p>'+esc(s.summary)+'</p></div></a>').join('')+'</div>';
}
const slides=[
 {title:'悬浮空化技术',en:'SUSPENDED CAVITATION',lead:'以新的空化发生方式，探索流体处理的更多可能。',copy:'我们从空化作用与流体路径出发，研究过程控制、介质适配和工程实现之间的关系，为不同场景建立可评估的处理方案。',href:'technology.html'},
 {title:'工艺研究与验证',en:'PROCESS RESEARCH',lead:'从具体介质出发，以实验理解技术价值。',copy:'围绕酒液、切削液和水处理等方向，以样品、运行参数和对照条件建立实验依据，关注处理效果与适用边界。',href:'applications.html'},
 {title:'演示样机与工程',en:'ENGINEERING DEVELOPMENT',lead:'从技术原理走向真实运行。',copy:'我们已完成可正常运行的演示样机，并开展实验对比。进一步的工程参数、材料适配与连续运行评价将支持行业应用。',href:'resources.html'}
];
const home='<section class="hero hero--motion"><div class="hero-media" aria-hidden="true"><picture><source media="(max-width: 700px)" srcset="assets/fluid-mobile.webp"><img src="assets/fluid-desktop.webp" alt="" fetchpriority="high" width="1440" height="810"></picture><video id="hero-fluid-video" muted loop playsinline preload="none" tabindex="-1" data-desktop="assets/fluid-desktop.mp4" data-mobile="assets/fluid-mobile.mp4"></video></div><div class="hero-inner container"><div class="hero-copy">'+label('FLUIDS FOR A CLEARER TOMORROW')+'<h1>看见流体<br>内部的变化</h1><p class="hero-lead">以悬浮空化为核心的流体反应与处理技术<br>让看不见的过程，变得可控、可用、可放大。</p><div class="hero-terms"><span>空化过程研究</span><span>液体处理</span><span>多行业应用</span></div><a class="demo-link" href="technology.html#videos"><span class="play">'+icon('play')+'</span>探索技术原理<span class="short-line"></span></a></div><aside class="hero-rail"><p>INSIDE<br>THE FLOW<br>A BRIGHTER<br>WORLD</p><div class="rail-quote">流动之间<br>蕴藏着改变的力量<span></span></div><small>CAVITATION<br>REACTION<br>PROCESS ENGINEERING<br>A CLEARER TOMORROW</small><div class="rail-controls"><span>01 / 03</span><button class="icon-button" data-hero-prev aria-label="上一条品牌主张">'+icon('chevron-left')+'</button><button class="icon-button" data-hero-next aria-label="下一条品牌主张">'+icon('chevron-right')+'</button></div></aside><a class="scroll-note" href="#technology">SCROLL<span></span></a><button class="motion-toggle" type="button" data-motion-toggle aria-controls="hero-fluid-video" hidden><span>播放流体动效</span></button></div></section>'+
 '<section class="value-band"><div class="container"><p>用流体科技<br>探索产业的更多可能</p><div><strong>6</strong><small>行业领域</small></div><div><strong>'+processes.length+'</strong><small>工艺研究方向</small></div><div><strong>悬浮空化</strong><small>核心技术</small></div><div><strong>已运行</strong><small>演示样机</small></div><a href="technology.html">技术让流动更有价值 '+arrow+'</a></div></section>'+
 homeTechnology()+
 '<section class="section sector-home"><div class="container">'+intro('APPLICATION SECTORS','一项核心技术<br>进入不同产业现场','酒类是当前最主要的代表方向，化工与环境构成重点应用。我们以行业需求为起点，逐步探索个人护理、医药与能源等领域。')+sectorCards()+'</div></section>'+
 '<section class="section flagship"><div class="container flagship-inner"><div class="flagship-copy">'+label('FEATURED APPLICATION / FOOD & BEVERAGE')+'<h2>酒类醇化<br>与品质优化</h2><p>面向酒厂的酒体处理与工艺研究。从真实酒样、理化分析和感官评价出发，探索醇化、风味协调与品质控制的新路径。</p>'+link('scene-alcohol.html','了解酒类应用','pill')+link('sector-food.html','更多食品与饮料场景')+'</div><figure><img loading="lazy" src="assets/wine.jpg" alt="葡萄酒与葡萄园行业影像"><figcaption>食品与饮料 · 行业场景</figcaption></figure></div></section>'+
 '<section class="section research-home"><div class="container">'+intro('KNOWLEDGE & INSIGHTS','持续研究<br>让技术更易理解','关注空化现象、工艺评价与产业应用。以清晰的技术知识，连接专业研究和真实生产问题。')+'<div class="article-list">'+articles.slice(0,3).map((a,i)=>'<a href="article-'+a.id+'.html"><span>0'+(i+1)+'</span><div><small>'+esc(a.category)+'</small><h3>'+esc(a.title)+'</h3><p>'+esc(a.excerpt)+'</p></div>'+arrow+'</a>').join('')+'</div>'+link('research.html','全部研究内容')+'</div></section>';
page('index.html','旋风流体', 'home',home,'以悬浮空化技术为核心，探索食品饮料、化工与环境等产业的流体处理新路径。','<script src="hero-motion.js"></script>');

page('technology.html','悬浮空化技术','technology',('<section class="inner-hero technology-hero"><div class="container">'+label('TECHNOLOGY & ENGINEERING')+'<h1>悬浮空化技术</h1><p>从空化发生方式出发，研究流体作用、过程控制与工程实现。</p></div></section>')+videoGallery('technology')+'<section class="section"><div class="container">'+crumbs([['技术与产品']])+intro('CORE PRINCIPLE','让流体作用<br>进入可评估的工程过程','空化已经在混合、乳化、萃取与水处理等领域得到应用。针对传统空化路线长期存在的空蚀、能耗、处理效率和工程放大问题，我们研发了新的空化发生方式。')+'<div class="technology-explanation"><div><h2>从原理到应用</h2><p>悬浮空化技术是旋风流体的核心技术方向。我们围绕空化作用区域、流体路径与运行条件，研究如何将技术应用于不同介质和工艺任务。</p><p>技术的应用价值需要结合具体条件评价。同一种介质在温度、流量、压力与循环次数变化时，可能产生不同结果。</p>'+metrics(['作用过程','工况匹配','工程运行','对照评价'])+link('applications.html','工艺研究方向')+'</div></div></div></section><section class="section pale"><div class="container">'+intro('ENGINEERING EVIDENCE','真实运行<br>是技术验证的起点','演示样机已完成并可正常运行，已有实验对比。公开测试报告将保留样品、设备版本、工况和适用条件。')+'<div class="text-columns"><div><h3>样品与条件</h3><p>记录介质来源、基础状态和处理目标，使每项试验具有明确的比较基线。</p></div><div><h3>运行与过程</h3><p>关注流量、压力、温度、循环方式与处理时间之间的关系。</p></div><div><h3>结果与边界</h3><p>结合场景评价理化、感官、稳定性及成本；避免将单个结果泛化到所有介质。</p></div></div>'+link('resources.html','工程与资料中心')+'</div></section>');

page('sectors.html','应用领域','sectors',innerHero('APPLICATION SECTORS','流体技术<br>连接不同产业','以行业需求组织应用，以具体工艺建立技术路径。')+'<section class="section"><div class="container">'+crumbs([['应用领域']])+sectorCards()+'</div></section>');
for(const [key,s] of sectors){
 const sceneList=s.scenarios;
 page('sector-'+key+'.html',s.name,'sectors',innerHero(s.english,esc(s.name),esc(s.summary),s.image)+'<nav class="sector-subnav" aria-label="行业导航"><div class="container">'+sectors.map(([k,t])=>'<a href="sector-'+k+'.html" '+(k===key?'aria-current="page"':'')+'>'+esc(t.name)+'</a>').join('')+'</div></nav><section class="section"><div class="container">'+crumbs([['应用领域','sectors.html'],[s.name]])+intro('SCENARIOS & PROCESSES','从产品场景<br>找到工艺方向',esc(s.intro||s.summary))+'<div class="scenario-grid">'+sceneList.map((x,i)=>'<a href="scene-'+x.id+'.html"><small>0'+(i+1)+'</small><h3>'+esc(x.title)+'</h3><p>'+esc(x.summary)+'</p>'+arrow+'</a>').join('')+'</div></div></section>');
 for(const x of sceneList){
  page('scene-'+x.id+'.html',x.title,'sectors',innerHero(s.english,esc(x.title),esc(x.summary),s.image)+'<section class="section"><div class="container">'+crumbs([['应用领域','sectors.html'],[s.name,'sector-'+key+'.html'],[x.title]])+'<div class="detail-columns"><section>'+label('THE NEED')+'<h2>关注真实的工艺问题</h2><p>'+esc(x.need)+'</p></section><section>'+label('THE APPROACH')+'<h2>建立对应的技术路径</h2><p>'+esc(x.approach)+'</p></section></div><div class="detail-heading">'+label('EVALUATION')+'<h2>评价指标</h2><p>以下为该场景的评价维度，具体处理效果以对应条件下的实验和工程验证为准。</p></div>'+metrics(x.metrics)+'<div class="detail-heading">'+label('RELATED PROCESSES')+'<h2>相关工艺</h2></div><div class="process-links">'+(x.processes||[]).filter(p=>data.processes[p]).map(p=>link('process-'+p+'.html',esc(data.processes[p].title))).join('')+'</div><div class="detail-heading"><h2>从样品到工程</h2></div><ol class="steps"><li><small>01</small><h3>需求界定</h3><p>明确介质、工况与目标。</p></li><li><small>02</small><h3>样品对照</h3><p>建立基线与试验条件。</p></li><li><small>03</small><h3>结果评价</h3><p>对照指标，识别适用边界。</p></li><li><small>04</small><h3>工程评估</h3><p>结合现场条件确认下一步。</p></li></ol>'+link('contact.html','与我们讨论该场景','pill')+'</div></section>',x.summary);
 }
}
page('applications.html','工艺能力','technology',innerHero('PROCESS CAPABILITIES','从流体变化<br>到具体工艺','同一项技术，在不同介质中回应不同的处理任务。')+'<section class="section"><div class="container">'+crumbs([['技术与产品','technology.html'],['工艺能力']])+'<p class="section-note">以下为工艺研究方向，不代表全部工艺均已完成商业验证。进入具体工艺，了解关注问题与评价方法。</p><div class="process-grid">'+processes.map(([id,p],i)=>'<a href="process-'+id+'.html"><small>'+String(i+1).padStart(2,'0')+' / '+esc(p.english)+'</small><h2>'+esc(p.title)+'</h2><p>'+esc(p.intro)+'</p>'+arrow+'</a>').join('')+'</div></div></section>');
for(const [id,p] of processes) page('process-'+id+'.html',p.title,'technology',innerHero(p.english,esc(p.title),esc(p.intro))+'<section class="section"><div class="container narrow">'+crumbs([['工艺能力','applications.html'],[p.title]])+'<h2>工艺评价</h2><p>'+esc(p.intro)+'</p><p>我们从样品性质和现有工艺出发，设置处理条件与对照。技术在不同场景中的适用性，需要通过实验结果、质量指标和工程要求综合判断。</p>'+metrics(p.metrics)+'<h2 class="detail-heading">相关行业</h2><div class="process-links">'+(p.sectors||[]).filter(k=>data.sectors[k]).map(k=>link('sector-'+k+'.html',esc(data.sectors[k].name))).join('')+'</div>'+link('contact.html','交流工艺需求','pill')+'</div></section>',p.intro);

page('resources.html','产品与资料','technology',innerHero('PRODUCTS & RESOURCES','以资料连接<br>技术与现场','了解技术形态、工艺方向，以及实验评价需要关注的条件。')+'<section class="section"><div class="container">'+crumbs([['技术与产品','technology.html'],['产品与资料']])+'<div class="technical-overview"><figure><img src="assets/reaction-module.webp" alt="技术模块概念示意"><figcaption>技术形态示意 · 非样机实拍</figcaption></figure><div>'+label('ENGINEERING DEVELOPMENT')+'<h2>演示样机</h2><p>旋风流体已完成可正常运行的演示样机，并开展实验对比。样机用于研究核心技术、介质处理与运行条件。</p><p>本页已提供空化科普、样机运行与仿真可视化、反应概念影像。更多设备参数与实验报告将在公开确认后补充。</p>'+link('technology.html','了解悬浮空化技术')+'</div></div><div class="detail-heading"><h2>公开资料</h2></div><div class="resource-list"><a href="application-guide.html"><span>'+icon('book-open')+'</span><div><h3>技术与应用概览</h3><p>公司定位、六类行业与工艺研究方向</p></div><small>在线阅读</small>'+arrow+'</a><a href="assets/application-guide.txt" download><span>'+icon('download')+'</span><div><h3>技术与应用概览</h3><p>可下载文本资料</p></div><small>TXT</small>'+arrow+'</a><a href="assets/sample-checklist.txt" download><span>'+icon('clipboard-list')+'</span><div><h3>应用需求准备清单</h3><p>介质、工况、目标及对照信息</p></div><small>TXT</small>'+arrow+'</a><div class="resource-pending"><span>'+icon('file-text')+'</span><div><h3>样机参数与实验报告</h3><p>公开资料整理中</p></div><small>待发布</small></div></div></div></section>'+videoGallery('resources'));

page('research.html','研究与动态','research',innerHero('KNOWLEDGE & INSIGHTS','理解流体<br>探索应用','从基础现象到工程评价，分享空化技术与工艺研究的知识。')+'<section class="section"><div class="container">'+crumbs([['研究与动态']])+'<div class="filters" aria-label="内容筛选">'+['全部','空化知识','技术研究','行业观察'].map((c,i)=>'<button type="button" data-filter="'+c+'" aria-pressed="'+(i===0)+'">'+c+'</button>').join('')+'</div><div class="article-list">'+articles.map((a,i)=>'<a data-category="'+esc(a.category)+'" href="article-'+a.id+'.html"><span>'+String(i+1).padStart(2,'0')+'</span><div><small>'+esc(a.category)+'</small><h2>'+esc(a.title)+'</h2><p>'+esc(a.excerpt)+'</p></div>'+arrow+'</a>').join('')+'</div><p class="filter-empty" hidden>当前分类暂无文章。</p></div></section>');
for(const a of articles) page('article-'+a.id+'.html',a.title,'research',innerHero(a.category,esc(a.title),esc(a.excerpt))+'<article class="section"><div class="container reading">'+crumbs([['研究与动态','research.html'],[a.title]])+(a.id==='understanding-cavitation'?videoCard('science','article'):'')+a.sections.map(s=>'<section><h2>'+esc(s.heading)+'</h2><p>'+esc(s.text)+'</p></section>').join('')+'<p class="article-footnote">技术知识内容用于一般交流，不等同于旋风流体具体设备的性能承诺。</p>'+link('research.html','返回研究与动态')+'</div></article>',a.excerpt);

page('about.html','关于旋风流体','about',innerHero('ABOUT TORNADO FLUID','围绕核心技术<br>持续拓展应用边界','Tornado Fluid Technologies · 旋风流体')+'<section class="section"><div class="container">'+crumbs([['关于我们']])+intro('OUR COMPANY','从技术发生<br>到产业应用','我们是一家围绕悬浮空化技术发展的技术平台公司。技术研发与多行业应用相互支持，构成旋风流体的发展方向。')+'<div class="about-rows"><div><small>01 / TECHNOLOGY</small><h2>专注核心技术</h2><p>持续研究空化发生方式、流体作用与工程实现，积累与不同介质相关的实验和应用认知。</p></div><div><small>02 / APPLICATION</small><h2>连接行业伙伴</h2><p>通过子公司、行业合作伙伴及授权体系，推进不同行业的产品开发与市场应用。</p></div><div><small>03 / VISION</small><h2>面向全球发展</h2><p>以清晰的技术表达、真实的工程依据与持续的研究交流，建立具有全球影响力的流体技术品牌。</p></div></div></div></section>');

page('contact.html','联系与咨询','contact',innerHero('CONTACT & ENQUIRY','从一个问题<br>开启技术交流','告诉我们您关注的介质、工艺或研究方向。')+'<section class="section"><div class="container contact-layout"><div>'+label('GET IN TOUCH')+'<h2>旋风流体</h2><p>Tornado Fluid Technologies</p><p id="contact-channel">企业联系方式即将公布。</p><p class="caption">您可以先整理应用需求，保存为本地摘要。当前页面不会上传或发送您的信息。</p>'+link('assets/sample-checklist.txt','查看需求准备清单')+'</div><form id="enquiry-form"><div class="form-grid"><label>姓名<input name="name" required autocomplete="name" maxlength="80"></label><label>公司或机构<input name="company" required autocomplete="organization" maxlength="120"></label><label>联系邮箱<input type="email" name="email" required autocomplete="email" maxlength="160"></label><label>关注领域<select name="sector">'+sectors.map(([key,s])=>'<option value="'+esc(s.name)+'">'+esc(s.name)+'</option>').join('')+'</select></label><label class="wide">您的问题<textarea name="message" required rows="5" maxlength="4000" placeholder="介质、现有工艺、处理量及期望结果"></textarea></label></div><button class="pill" type="submit">保存需求摘要 '+icon('download')+'</button><p id="form-status" role="status"></p></form></div></section>');
page('privacy.html','隐私说明','about',innerHero('PRIVACY','隐私说明','我们重视信息收集的必要性与透明度。')+'<section class="section"><div class="container reading"><h2>当前页面的数据处理</h2><p>网站搜索在您的浏览器中执行。当前联系表单仅生成由您主动下载的本地需求摘要，不向服务器提交姓名、邮箱或留言。</p><h2>存储与统计</h2><p>本版本不使用行为分析工具或广告追踪，也不写入用于营销的 Cookie。在线预览由 GitHub Pages 托管。GitHub 可能为提供服务及保障安全处理访问记录，具体处理方式请参阅 <a href="https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement">GitHub 隐私声明</a>。</p><h2>正式联系服务</h2><p>联系系统启用前，将补充运营主体、联系渠道、信息用途、保存期限及删除申请方式。本说明不构成已开通在线咨询服务的承诺。</p></div></section>');
page('terms.html','使用条款','about',innerHero('TERMS OF USE','使用条款','技术信息的用途与边界。')+'<section class="section"><div class="container reading"><h2>技术信息</h2><p>行业与工艺页面介绍应用研究方向。具体产品性能、运行参数及处理结果以双方确认的技术文件和对应测试条件为准。</p><h2>视觉资料</h2><p>首页流体动画与互动雕塑为品牌概念视觉，非空化物理仿真。视频按科普、样机录像与仿真可视化、AI 生成概念影像分别标注；模块概念图和行业参考照片不代表实际设备或客户案例。</p><h2>资料使用</h2><p>公开资料可用于了解公司与开展技术交流。正式商业合作、产品采购及知识产权使用以书面协议为准。</p></div></section>');
page('international.html','Tornado Fluid Technologies','about',innerHero('INTERNATIONAL OVERVIEW','Tornado Fluid<br>Technologies','Suspended Cavitation Technology. Research, engineering and sector applications.')+'<section class="section"><div class="container reading"><h2>About Tornado Fluid</h2><p>We are a technology company focused on suspended cavitation. We develop new approaches to cavitation generation and evaluate their applications across food and beverages, chemicals and environmental processes.</p><h2>From research to engineering</h2><p>A working demonstrator has been built and comparative experiments have been conducted. Application suitability and performance must be assessed against specific media, operating conditions and process requirements.</p><h2>Areas of focus</h2><p>Alcoholic beverage refinement is a key application. Cutting fluids and water treatment are additional focus areas, alongside longer-term opportunities in personal care, pharmaceuticals and energy.</p><p>The full English website will follow the finalized Chinese content. This page provides a company overview.</p>'+link('sectors.html','Explore application sectors')+link('contact.html','Contact and enquiry')+'</div></section>');
page('application-guide.html','技术与应用概览','technology',innerHero('PUBLICATION','技术与应用概览','旋风流体 · 悬浮空化技术')+'<section class="section"><div class="container reading"><h2>公司与技术</h2><p>旋风流体围绕悬浮空化技术持续研发，通过实验与工程实现推动多行业应用。</p>'+sectors.map(([k,s])=>'<section><h2>'+esc(s.name)+'</h2><p>'+esc(s.summary)+'</p><ul>'+s.scenarios.map(x=>'<li>'+esc(x.title)+'</li>').join('')+'</ul></section>').join('')+'<h2>工艺研究方向</h2><p>'+processes.map(([k,p])=>esc(p.title)).join('、')+'</p>'+link('assets/application-guide.txt','下载文本版')+'</div></section>');
fs.writeFileSync(path.join(root,'assets/application-guide.txt'),'旋风流体\nTornado Fluid Technologies\n核心技术：悬浮空化技术\n\n'+sectors.map(([k,s])=>s.name+'\n'+s.summary+'\n'+s.scenarios.map(x=>'- '+x.title).join('\n')).join('\n\n')+'\n\n所列内容为应用研究方向；具体效果需按样品与运行条件验证。\n');
fs.writeFileSync(path.join(root,'assets/sample-checklist.txt'),'旋风流体 应用需求准备清单\n\n1. 所属行业、产品及介质\n2. 当前工艺和主要问题\n3. 处理量、温度、黏度、固含量等已知条件\n4. 期望评价指标\n5. 样品可用性与现有对照数据\n6. 现场接入与材料约束\n7. 联系人及企业信息\n\n请在开始实验前确认样品处理要求、保密事项与技术目标。\n');
fs.writeFileSync(path.join(root,'search-index.js'),'window.VORTEX_SEARCH='+JSON.stringify(search)+';');
fs.writeFileSync(path.join(root,'404.html'),'<!doctype html><html lang="zh-CN"><meta charset="utf-8"><title>页面未找到 · 旋风流体</title><link rel="stylesheet" href="site.css"><main class="container section"><h1>页面未找到</h1><p>请返回首页或通过行业目录继续浏览。</p><a class="pill" href="index.html">返回首页</a></main></html>');
fs.writeFileSync(path.join(root,'robots.txt'),'User-agent: *\nAllow: /\n'+(baseUrl?'Sitemap: '+baseUrl+'sitemap.xml\n':''));
if(baseUrl)fs.writeFileSync(path.join(root,'sitemap.xml'),'<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+search.map(x=>'<url><loc>'+esc(new URL(x.url,baseUrl).href)+'</loc></url>').join('')+'</urlset>');
console.log('Built '+search.length+' static pages.');
