const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict');
const {pathToFileURL}=require('url');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const root=path.resolve(__dirname,'..'),out=path.resolve(process.env.WATER_CHECK_OUT||path.join(root,'work/water-checks'));
fs.mkdirSync(out,{recursive:true});
const server=http.createServer((req,res)=>{
 const file=path.resolve(root,'.'+decodeURIComponent(new URL(req.url,'http://localhost').pathname));
 if(!file.startsWith(root+path.sep)||!fs.existsSync(file)||!fs.statSync(file).isFile()){res.writeHead(404);return res.end();}
 const type={'.html':'text/html;charset=utf-8','.css':'text/css','.js':'text/javascript','.webp':'image/webp','.mp4':'video/mp4','.svg':'image/svg+xml'}[path.extname(file)]||'application/octet-stream';
 res.writeHead(200,{'Content-Type':type,'Content-Length':fs.statSync(file).size});fs.createReadStream(file).pipe(res);
});
const checks=[],errors=[];let browser;
async function run(){
 await new Promise(r=>server.listen(0,'127.0.0.1',r));
 const base=process.env.WATER_CHECK_URL||`http://127.0.0.1:${server.address().port}/`;
 browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{})});
 const page=await browser.newPage({viewport:{width:1440,height:1000}});
 page.on('pageerror',e=>errors.push(e.message));
 page.on('console',m=>{if(m.type()==='error'&&/shader|framebuffer|GL_INVALID/.test(m.text()))errors.push(m.text());});
 const visit=name=>page.goto(new URL(name,base).href);
 const canvas=()=>page.locator('.water-canvas');
 const frames=()=>canvas().evaluate(c=>+c.dataset.frames);
 const image=()=>canvas().evaluate(c=>c.toDataURL());
 const scroll=async y=>{await page.evaluate(top=>window.scrollTo({top,behavior:'instant'}),y);};
 const active=()=>page.waitForFunction(()=>document.querySelector('.water-background').dataset.waterState==='active');
 for(const width of [1440,390,360]){
  await page.setViewportSize({width,height:width===1440?1000:844});await visit('technology.html');
  assert.equal(await page.locator('h1').innerText(),'悬浮空化技术');
  assert.equal(await page.locator('#primary-nav a[aria-current]').innerText(),'技术与产品');
  assert.deepEqual(await page.locator('main video').evaluateAll(vs=>vs.map(v=>v.id)),['film-technology-prototype','film-technology-science','film-technology-concept']);
  assert.equal(await page.locator('main img[src*="reaction-module"]').count(),0);
  const rect=await page.locator('main video').first().boundingBox();assert.ok(rect.y>70&&rect.y+rect.height<=(width===1440?1000:844));
  const flow=await page.locator('main').evaluate(e=>[...e.querySelectorAll('video,h2')].map(n=>n.tagName==='VIDEO'?n.id:n.innerText));
  assert.ok(flow.indexOf('film-technology-concept')<flow.findIndex(s=>s.includes('让流体作用')));
  assert.equal(await canvas().count(),0);
  await page.screenshot({path:path.join(out,`technology-${width}.png`)});
  checks.push(`${width}px: existing headings, prototype first, three videos before explanations, no concept device image`);
  await scroll(650);await active();
  assert.equal(await canvas().getAttribute('data-grid'),width===1440?'128':'64');
  const before=await image();await scroll(790);await page.waitForTimeout(140);
  assert.notEqual(await image(),before);
  assert.equal(await page.locator('.water-background').getAttribute('data-direction'),'down');
  await scroll(640);await page.waitForTimeout(120);
  assert.equal(await page.locator('.water-background').getAttribute('data-direction'),'up');
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  const count=await frames();await page.waitForTimeout(400);assert.ok(await frames()-count<=(width===1440?14:10));
  await page.waitForFunction(()=>document.querySelector('.water-background').dataset.waterState==='idle');
  const resting=await frames();await page.waitForTimeout(350);assert.equal(await frames(),resting);
  checks.push(`${width}px: water pixels change, reverse scroll, correct grid/FPS cap, settles and stops`);
 }
 await page.setViewportSize({width:1440,height:1000});await visit('technology.html');await scroll(700);await active();
 const first=page.locator('#film-technology-prototype');await first.scrollIntoViewIfNeeded();
 await first.locator('..').locator('[data-media-start]').click();await page.waitForFunction(()=>!document.querySelector('#film-technology-prototype').paused);
 await page.waitForFunction(()=>document.querySelector('.water-background').dataset.waterState==='paused');
 const paused=await frames();await scroll(650);await page.waitForTimeout(250);assert.equal(await frames(),paused);
 await page.setViewportSize({width:390,height:844});
 await first.evaluate(v=>v.pause());await scroll(500);await active();
 assert.equal(await canvas().getAttribute('data-grid'),'64');
 await page.setViewportSize({width:1440,height:1000});await scroll(820);await active();
 assert.equal(await canvas().getAttribute('data-grid'),'128');
 checks.push('Viewport changes during video playback apply correct grid on resume');
 checks.push('Playing a content video pauses water; scrolling after pause resumes water');
 await page.emulateMedia({reducedMotion:'reduce'});
 await page.waitForFunction(()=>getComputedStyle(document.querySelector('.water-canvas')).display==='none');
 await page.waitForTimeout(100);const reducedFrames=await frames();await scroll(900);await page.waitForTimeout(250);assert.equal(await frames(),reducedFrames);
 await page.emulateMedia({reducedMotion:'no-preference'});await scroll(750);await active();
 checks.push('Reduced-motion hides and stops water; restoring preference and scrolling resumes it');
 await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'));});
 const hiddenFrames=await frames();await page.waitForTimeout(200);assert.equal(await frames(),hiddenFrames);
 await page.evaluate(()=>{delete document.hidden;document.dispatchEvent(new Event('visibilitychange'));});await scroll(850);await active();
 checks.push('Background tab handler stops GPU drawing');
 await page.mouse.move(1300,850);const lastInput=await page.locator('.water-background').getAttribute('data-direction');
 await page.waitForFunction(()=>document.querySelector('.water-background').dataset.waterState==='idle');
 const idleFrames=await frames();await page.mouse.move(120,300,{steps:20});await page.waitForTimeout(150);assert.equal(await frames(),idleFrames);
 assert.equal(await page.locator('.water-background').getAttribute('data-direction'),lastInput);checks.push('Mouse movement does not drive the background');
 const quiet=await browser.newPage({reducedMotion:'reduce'});const quietRequests=[];
 quiet.on('request',r=>{if(r.url().includes('water-surface.js'))quietRequests.push(r.url());});await quiet.goto(new URL('technology.html',base).href);await quiet.evaluate(()=>scrollTo({top:650,behavior:'instant'}));await quiet.waitForTimeout(200);
 assert.equal(quietRequests.length,0);assert.equal(await quiet.locator('.water-canvas').count(),0);checks.push('Reduced-motion initial load uses static poster without requesting renderer');
 const unsupported=await browser.newPage();await unsupported.addInitScript(()=>{const original=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type,...args){return type==='webgl2'?null:original.call(this,type,...args);};});
 await unsupported.goto(new URL('technology.html',base).href);await unsupported.evaluate(()=>scrollTo({top:650,behavior:'instant'}));await unsupported.waitForFunction(()=>document.querySelector('.water-background').dataset.waterState==='fallback');
 assert.equal(await unsupported.locator('.water-canvas').count(),0);await unsupported.locator('#search-open').click();assert.ok(await unsupported.locator('#search-dialog').isVisible());checks.push('Unavailable WebGL retains static background and working navigation');
 const offline=await browser.newPage();await offline.route('**/water-surface.js',r=>r.abort());await offline.goto(new URL('technology.html',base).href);await offline.evaluate(()=>scrollTo({top:650,behavior:'instant'}));await offline.waitForFunction(()=>document.querySelector('.water-background').dataset.waterState==='fallback');checks.push('Renderer network failure retains fallback');
 await canvas().evaluate(c=>c.getContext('webgl2').getExtension('WEBGL_lose_context').loseContext());
 await page.waitForFunction(()=>document.querySelector('.water-background').dataset.waterState==='fallback');checks.push('Lost graphics context safely returns to static poster');
 await page.goto(pathToFileURL(path.join(root,'technology.html')).href);await scroll(650);await active();checks.push('Direct local-file water playback works');
 await visit('index.html');assert.equal(await page.locator('.hero--motion').count(),1);assert.equal(await page.locator('[data-fluid-stage]').count(),0);assert.equal(await page.locator('main video[data-content-video]').count(),0);
 await scroll(1300);assert.ok(await page.locator('.header').evaluate(e=>Math.abs(e.getBoundingClientRect().top)<1));await page.locator('#primary-nav').getByRole('link',{name:'技术与产品',exact:true}).click();assert.ok(page.url().endsWith('technology.html'));checks.push('Home hero and compact layout preserved; fixed navigation remains clickable');
 assert.deepEqual(errors,[]);
 fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({checks,errors},null,2));console.log(JSON.stringify({passed:checks.length,checks,errors},null,2));
}
run().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{await browser?.close();server.close();});
